version: "2.1"

services:
  database:
    container_name: od-database
    image: docker.pkg.github.com/open-discourse/open-discourse/database:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

  graphql:
    container_name: od-graphql
    image: docker.pkg.github.com/open-discourse/open-discourse/graphql:latest
    environment:
      - POSTGRES_DB_NAME=next
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=postgres
      - POSTGRES_DB_HOST=database
      - POSTGRES_DB_PORT=5432
      - ENABLE_GRAPHIQL=true
      - CORS_ORIGIN=http://167.99.244.228/
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"

  proxy:
    container_name: od-proxy
    image: docker.pkg.github.com/open-discourse/open-discourse/proxy:latest
    depends_on:
      graphql:
        condition: service_started
    environment:
      - GRAPHQL_ENDPOINT=http://od-graphql:5000/graphql
      - CACHE_EXPIRATION=100000
    ports:
      - "80:80"
