version: "2.1"

services:
  traefik:
    image: traefik:v2.3
    ports:
      - "80:80"
      - "443:443"
      - "5300:5300"
      - "8080:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./traefik_config.yml:/traefik_config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.insecure=true
      - --api.dashboard=true
      # - --api.debug=true
      # - --log.level=DEBUG
      
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/traefik_config.yml
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --entrypoints.web-proxy.address=:5300
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --certificatesresolvers.mytlschallenge.acme.email=oliver.franke@limebit.de
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json

  database:
    container_name: od-database
    image: docker.pkg.github.com/open-discourse/open-discourse/database:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

  graphql:
    container_name: od-graphql
    image: docker.pkg.github.com/open-discourse/open-discourse/graphql:latest
    environment:
      - POSTGRES_DB_NAME=next
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=postgres
      - POSTGRES_DB_HOST=database
      - POSTGRES_DB_PORT=5432
      - ENABLE_GRAPHIQL=true
      - CORS_ORIGIN=http://67.207.79.172/
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"

  proxy:
    container_name: od-proxy
    image: docker.pkg.github.com/open-discourse/open-discourse/proxy:latest
    depends_on:
      graphql:
        condition: service_started
    environment:
      - GRAPHQL_ENDPOINT=http://od-graphql:5000/graphql
      - CACHE_EXPIRATION=100000
      - QUERY_LIMIT=100
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`api.opendiscourse.de`)"
      - "traefik.http.routers.proxy.entrypoints=web-proxy"
      - "traefik.http.routers.proxy.tls.certresolver=mytlschallenge"

  frontend:
    container_name: od-frontend
    image: docker.pkg.github.com/open-discourse/open-discourse/frontend:latest
    depends_on:
      proxy:
        condition: service_started
    environment:
      - PROXY_ENDPOINT=https://api.opendiscourse.de:5300
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`api.opendiscourse.de`)"
      - "traefik.http.routers.frontend.entrypoints=web-secure"
      - "traefik.http.routers.frontend.tls.certresolver=mytlschallenge"
